-- AlterTable
ALTER TABLE "GradeReportLine" ALTER COLUMN "grade" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "GradeReportProblem" ALTER COLUMN "score" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "possible" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "GradeReportQuestion" ALTER COLUMN "score" SET DATA TYPE DOUBLE PRECISION;
