services:
    db:
        container_name: 'stoocs-db'
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - db-data:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
            interval: 10s
            timeout: 10s
            retries: 5
            start_period: 30s

    app:
        container_name: 'stoocs'
        restart: always
        env_file:
            - .env
        depends_on:
            db:
                condition: service_healthy
        build: .
        command: ['/usr/local/bin/startup.sh']

    nginx:
        container_name: 'stooocs-nginx'
        image: nginx
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            # Uncomment the following line to enable SSL
            # - ${SSL_CERT_PATH}:/etc/nginx/ssl:ro
        ports:
            - '80:80'
            - '443:443'
        depends_on:
            - app

volumes:
    db-data:
