version: '3.8'
services:
  db:
    container_name: 'stooc-db'
    image: postgres
    restart: always
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  app:
    container_name: 'stooc'
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    build: .
    command: ["/usr/local/bin/startup.sh"]
    ports:
      - "80:3000"

volumes:
  db-data: