import { Argon2id } from 'oslo/password';
import { generateId } from 'lucia';

export const users = [
    {
        id: generateId(15),
        email: 'nathan@mail.com',
        password: await new Argon2id().hash('nathan'),
        firstname: 'Nathan',
        lastname: 'Viaud',
    },
    {
        id: generateId(15),
        email: 'marie.collin@mail.com',
        password: await new Argon2id().hash('password'),
        firstname: 'Marie',
        lastname: 'Collin',
    },
    {
        id: generateId(15),
        email: 'benoit.rospars@mail.com',
        password: await new Argon2id().hash('password'),
        firstname: 'Benoit',
        lastname: 'Rospars',
    },
    {
        id: generateId(15),
        email: 'laurence.farhi@mail.com',
        password: await new Argon2id().hash('password'),
        firstname: 'Laurence',
        lastname: 'Farhi',
    },
    {
        id: generateId(15),
        email: 'sherazade@mail.com',
        password: await new Argon2id().hash('password'),
        firstname: 'Sherazade',
        lastname: 'Djeballah',
    },
    {
        id: generateId(15),
        email: 'madeline.montigny@mail.com',
        password: await new Argon2id().hash('password'),
        firstname: 'Madeline',
        lastname: 'Montigny',
    },
    {
        id: generateId(15),
        email: 'sabah.khalfa@mail.com',
        password: await new Argon2id().hash('password'),
        firstname: 'Sabah',
        lastname: 'Khalfa',
    },
    {
        id: generateId(15),
        email: 'aurelie@mail.com',
        password: await new Argon2id().hash('password'),
        firstname: 'Aurelie',
        lastname: 'Lagarrigue',
    },
    {
        id: generateId(15),
        email: 'jm@mail.com',
        password: await new Argon2id().hash('password'),
        firstname: 'Jean-Marc',
        lastname: 'Hasenfratz',
    },
    {
        id: generateId(15),
        email: 'laetitia@mail.com',
        password: await new Argon2id().hash('password'),
        firstname: 'Laetitia',
        lastname: 'Ecrement',
    },
    {
        id: generateId(15),
        email: 'christelle@mail.com',
        password: await new Argon2id().hash('password'),
        firstname: 'Christelle',
        lastname: 'Mariais',
    },
    {
        id: generateId(15),
        email: 'invite@mail.com',
        password: await new Argon2id().hash('password'),
        firstname: 'John',
        lastname: 'Doe',
        rolename: 'Guest',
    },
    {
        id: generateId(15),
        email: 'invite2@mail.com',
        password: await new Argon2id().hash('password'),
        firstname: 'Jane',
        lastname: 'Doe',
        rolename: 'Guest',
    },
    {
        id: generateId(15),
        email: 'invite3@mail.com',
        password: await new Argon2id().hash('password'),
        firstname: 'Bob',
        lastname: 'Doe',
        rolename: 'Guest',
    },
    {
        id: generateId(15),
        email: 'invite4@mail.com',
        password: await new Argon2id().hash('password'),
        firstname: 'Billy',
        lastname: 'Doe',
        rolename: 'Guest',
    },
    {
        id: generateId(15),
        email: 'invite5@mail.com',
        password: await new Argon2id().hash('password'),
        firstname: 'Jenny',
        lastname: 'Doe',
        rolename: 'Guest',
    },
    {
        id: generateId(15),
        email: 'invite6@mail.com',
        password: await new Argon2id().hash('password'),
        firstname: 'Bailey',
        lastname: 'Doe',
        rolename: 'Guest',
    },
];
